bot_token: ''

gm_list: [] # 管理员列表

eh_cookies: [{  # eh_cookie可以为多个，请使用里站cookie，如果你的网络可以直接更新里站cookie那么igneous可以不填写。
  ipb_member_id: "",
  ipb_pass_hash: "",
  igneous: "",
  }
]

mysql:
  host: "localhost"  # MySQL 地址
  prot: 3306         # MySQL 端口
  user: "root"       # MySQL 用户名
  password: "password"  # MySQL 密码
  db: "eh_arc" # 数据库名称